# Generated by Django 4.0.5 on 2024-01-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='language',
        ),
    ]
